### ISSUE TITLE
data set download link on is invalid

### ISSUE THREAD

**Issue by zhangqinghua1008** [CancerDataScience/NuCLS#1]
Hello, The data set download link on ““ https://sites.google.com/view/nucls ”” is invalid.
Can you help to see what's going on, thank you!

**Comment by kheffah** [comment]
@zhangqinghua1008 Are you sure? The landing page doesn't actually have any download links. 
> To download the single-rater datasets, you can visit [this page](https://sites.google.com/view/nucls/single-rater). 
> To download the multi-rater datasets, you can visit [this page](https://sites.google.com/view/nucls/multi-rater).
Let me know if this answers your question. If now, please point me to which specific link is broken and I'd be happy to address this.

**Comment by kheffah** [comment]
I assume this question is answered. If not, feel free to comment & re-open.

**Comment by zhangqinghua1008** [comment]
thank you，i can open it
